/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.x0;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author edwinhernandezlopez
 */
public class Juego extends javax.swing.JFrame {

    String jugador = "X";

    int f1c1 = 0;
    int f1c2 = 0;
    int f1c3 = 0;
    int f2c1 = 0;
    int f2c2 = 0;
    int f2c3 = 0;
    int f3c1 = 0;
    int f3c2 = 0;
    int f3c3 = 0;
    
    int ganarFila1=3;
    int ganarFila2=3;
    int ganarFila3=3;
    
    int ganarColumna1=3;
    int ganarColumna2=3;
    int ganarColumna3=3;
    
    

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        this.setLocationRelativeTo(null);
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        X0 = new javax.swing.JLabel();
        jLabelX = new javax.swing.JLabel();
        labelNombreX = new javax.swing.JLabel();
        jLabel0 = new javax.swing.JLabel();
        labelNombre0 = new javax.swing.JLabel();
        turno = new javax.swing.JLabel();
        Ingrese = new javax.swing.JLabel();
        jLabelFila = new javax.swing.JLabel();
        jLabelColumna = new javax.swing.JLabel();
        CoordenadaColumna = new javax.swing.JTextField();
        CoordenadaFila = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jPanelRablero = new javax.swing.JPanel();
        jPanelF1C1 = new javax.swing.JPanel();
        jLabelF1C1 = new javax.swing.JLabel();
        jPanelF1C2 = new javax.swing.JPanel();
        jLabelF1C2 = new javax.swing.JLabel();
        jPanelF1C3 = new javax.swing.JPanel();
        jLabelF1C3 = new javax.swing.JLabel();
        jPanelF2C1 = new javax.swing.JPanel();
        jLabelF2C1 = new javax.swing.JLabel();
        jPanelF2C2 = new javax.swing.JPanel();
        jLabelF2C2 = new javax.swing.JLabel();
        jPanelF2C3 = new javax.swing.JPanel();
        jLabelF2C3 = new javax.swing.JLabel();
        jPanelF3C1 = new javax.swing.JPanel();
        jLabelF3C1 = new javax.swing.JLabel();
        jPanelF3C2 = new javax.swing.JPanel();
        jLabelF3C2 = new javax.swing.JLabel();
        jPanelF3C3 = new javax.swing.JPanel();
        jLabelF3C3 = new javax.swing.JLabel();
        Resultado = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setText("Nombre 0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        X0.setFont(new java.awt.Font("Helvetica Neue", 1, 60)); // NOI18N
        X0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X0.setText("X 0");

        jLabelX.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabelX.setText("X: ");

        labelNombreX.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        labelNombreX.setText("Nombre X");

        jLabel0.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel0.setText("0: ");

        labelNombre0.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        labelNombre0.setText("Nombre 0");

        turno.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        turno.setText("Turno de X");

        Ingrese.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Ingrese.setText("Ingrese las coordenadas del movimiento:");

        jLabelFila.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFila.setText("Fila");

        jLabelColumna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelColumna.setText("Columna");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAceptarMouseClicked(evt);
            }
        });

        jPanelRablero.setBackground(new java.awt.Color(0, 0, 0));

        jLabelF1C1.setBackground(new java.awt.Color(255, 0, 102));
        jLabelF1C1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF1C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelF1C1.setText(" ");

        javax.swing.GroupLayout jPanelF1C1Layout = new javax.swing.GroupLayout(jPanelF1C1);
        jPanelF1C1.setLayout(jPanelF1C1Layout);
        jPanelF1C1Layout.setHorizontalGroup(
            jPanelF1C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF1C1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF1C1Layout.setVerticalGroup(
            jPanelF1C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF1C1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabelF1C2.setBackground(new java.awt.Color(255, 0, 102));
        jLabelF1C2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF1C2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF1C2Layout = new javax.swing.GroupLayout(jPanelF1C2);
        jPanelF1C2.setLayout(jPanelF1C2Layout);
        jPanelF1C2Layout.setHorizontalGroup(
            jPanelF1C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF1C2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF1C2Layout.setVerticalGroup(
            jPanelF1C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF1C2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelF1C3.setBackground(new java.awt.Color(255, 0, 102));
        jLabelF1C3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF1C3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF1C3Layout = new javax.swing.GroupLayout(jPanelF1C3);
        jPanelF1C3.setLayout(jPanelF1C3Layout);
        jPanelF1C3Layout.setHorizontalGroup(
            jPanelF1C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF1C3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelF1C3Layout.setVerticalGroup(
            jPanelF1C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF1C3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelF2C1.setBackground(new java.awt.Color(255, 0, 102));
        jLabelF2C1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF2C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF2C1Layout = new javax.swing.GroupLayout(jPanelF2C1);
        jPanelF2C1.setLayout(jPanelF2C1Layout);
        jPanelF2C1Layout.setHorizontalGroup(
            jPanelF2C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF2C1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF2C1Layout.setVerticalGroup(
            jPanelF2C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF2C1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabelF2C2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF2C2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF2C2Layout = new javax.swing.GroupLayout(jPanelF2C2);
        jPanelF2C2.setLayout(jPanelF2C2Layout);
        jPanelF2C2Layout.setHorizontalGroup(
            jPanelF2C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF2C2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF2C2Layout.setVerticalGroup(
            jPanelF2C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF2C2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabelF2C3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF2C3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF2C3Layout = new javax.swing.GroupLayout(jPanelF2C3);
        jPanelF2C3.setLayout(jPanelF2C3Layout);
        jPanelF2C3Layout.setHorizontalGroup(
            jPanelF2C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF2C3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF2C3Layout.setVerticalGroup(
            jPanelF2C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF2C3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabelF3C1.setBackground(new java.awt.Color(255, 0, 102));
        jLabelF3C1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF3C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF3C1Layout = new javax.swing.GroupLayout(jPanelF3C1);
        jPanelF3C1.setLayout(jPanelF3C1Layout);
        jPanelF3C1Layout.setHorizontalGroup(
            jPanelF3C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF3C1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF3C1Layout.setVerticalGroup(
            jPanelF3C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF3C1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabelF3C2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF3C2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF3C2Layout = new javax.swing.GroupLayout(jPanelF3C2);
        jPanelF3C2.setLayout(jPanelF3C2Layout);
        jPanelF3C2Layout.setHorizontalGroup(
            jPanelF3C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF3C2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF3C2Layout.setVerticalGroup(
            jPanelF3C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF3C2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabelF3C3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF3C3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF3C3Layout = new javax.swing.GroupLayout(jPanelF3C3);
        jPanelF3C3.setLayout(jPanelF3C3Layout);
        jPanelF3C3Layout.setHorizontalGroup(
            jPanelF3C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF3C3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF3C3Layout.setVerticalGroup(
            jPanelF3C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF3C3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelRableroLayout = new javax.swing.GroupLayout(jPanelRablero);
        jPanelRablero.setLayout(jPanelRableroLayout);
        jPanelRableroLayout.setHorizontalGroup(
            jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRableroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelRableroLayout.createSequentialGroup()
                        .addComponent(jPanelF1C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelF1C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelF1C3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelRableroLayout.createSequentialGroup()
                        .addComponent(jPanelF2C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelF2C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelF2C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRableroLayout.createSequentialGroup()
                        .addComponent(jPanelF3C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelF3C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelF3C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRableroLayout.setVerticalGroup(
            jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRableroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRableroLayout.createSequentialGroup()
                        .addGroup(jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelF1C3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelF1C1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelF1C2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelF2C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelF2C3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelF2C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelF3C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelF3C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelF3C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelRablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turno)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelX)
                                    .addComponent(jLabel0))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNombre0)
                                    .addComponent(labelNombreX, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(Ingrese)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CoordenadaFila, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CoordenadaColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(X0)))
                .addGap(0, 100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelFila)
                                .addGap(51, 51, 51)
                                .addComponent(jLabelColumna)))
                        .addGap(71, 71, 71))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(X0)
                .addGap(69, 69, 69)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreX)
                    .addComponent(jLabelX))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre0)
                    .addComponent(jLabel0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(turno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingrese)
                    .addComponent(CoordenadaFila, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CoordenadaColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFila)
                    .addComponent(jLabelColumna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAceptar)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelRablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAceptarMouseClicked

        int fila = Integer.parseInt(CoordenadaFila.getText());
        int columna = Integer.parseInt(CoordenadaColumna.getText());
        
        int cambio=0;

        if (fila == 1 && columna == 1 && f1c1 == 0) {
            jLabelF1C1.setText(jugador);
            f1c1 = 1;
            ganarFila1--;
            ganarColumna1--;
            cambio=1;

        } else if (fila == 1 && columna == 2 && f1c2 == 0) {
            jLabelF1C2.setText(jugador);
            f1c2 = 1;
            ganarFila1--;
            ganarColumna2--;
            cambio=1;

        } else if (fila == 1 && columna == 3 && f1c3 == 0) {
            jLabelF1C3.setText(jugador);
            f1c3 = 1;
            ganarFila1--;
            ganarColumna3--;
            cambio=1;

        } else if (fila == 2 && columna == 1 && f2c1 == 0) {
            jLabelF2C1.setText(jugador);
            f2c1 = 1;
            ganarFila2--;
            ganarColumna1--;
            cambio=1;

        } else if (fila == 2 && columna == 2 && f2c2 == 0) {
            jLabelF2C2.setText(jugador);
            f2c2 = 1;
            ganarFila2--;
            ganarColumna2--;
            cambio=1;

        } else if (fila == 2 && columna == 3 && f2c3 == 0) {
            jLabelF2C3.setText(jugador);
            f2c3 = 1;
            ganarFila2--;
            ganarColumna3--;
            cambio=1;

        } else if (fila == 3 && columna == 1 && f3c1 == 0) {
            jLabelF3C1.setText(jugador);
            f3c1 = 1;
            ganarFila3--;
            ganarColumna1--;
            cambio=1;

        } else if (fila == 3 && columna == 2 && f3c2 == 0) {
            jLabelF3C2.setText(jugador);
            f3c2 = 1;
            ganarFila3--;
            ganarColumna2--;
            cambio=1;

        } else if (fila == 3 && columna == 3 && f3c3 == 0) {
            jLabelF3C3.setText(jugador);
            f3c3 = 1;
            ganarFila3--;
            ganarColumna3--;
            cambio=1;
        }

        if (ganarFila1==0){
            String resultado="Ganó "+jugador;
            Resultado.setText(resultado);
        } else if (ganarFila2==0){
            String resultado="Ganó "+jugador;
            Resultado.setText(resultado);
        } else if (ganarFila3==0){
            String resultado="Ganó "+jugador;
            Resultado.setText(resultado);
        } else if (ganarColumna1==0){
            String resultado="Ganó "+jugador;
            Resultado.setText(resultado);
        } else if (ganarColumna2==0){
            String resultado="Ganó "+jugador;
            Resultado.setText(resultado);
        } else if (ganarColumna3==0){
            String resultado="Ganó "+jugador;
            Resultado.setText(resultado);
        }
        
        if (jugador.equals("X") && cambio==1) {
            jugador = "O";
            turno.setText("Turno de 0");

        } else if (jugador.equals("O") && cambio==1){
            jugador = "X";
            turno.setText("Turno de X");
        }
        
        

    }//GEN-LAST:event_jButtonAceptarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CoordenadaColumna;
    private javax.swing.JTextField CoordenadaFila;
    private javax.swing.JLabel Ingrese;
    private javax.swing.JLabel Resultado;
    private javax.swing.JLabel X0;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelColumna;
    private javax.swing.JLabel jLabelF1C1;
    private javax.swing.JLabel jLabelF1C2;
    private javax.swing.JLabel jLabelF1C3;
    private javax.swing.JLabel jLabelF2C1;
    private javax.swing.JLabel jLabelF2C2;
    private javax.swing.JLabel jLabelF2C3;
    private javax.swing.JLabel jLabelF3C1;
    private javax.swing.JLabel jLabelF3C2;
    private javax.swing.JLabel jLabelF3C3;
    private javax.swing.JLabel jLabelFila;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelF1C1;
    private javax.swing.JPanel jPanelF1C2;
    private javax.swing.JPanel jPanelF1C3;
    private javax.swing.JPanel jPanelF2C1;
    private javax.swing.JPanel jPanelF2C2;
    private javax.swing.JPanel jPanelF2C3;
    private javax.swing.JPanel jPanelF3C1;
    private javax.swing.JPanel jPanelF3C2;
    private javax.swing.JPanel jPanelF3C3;
    private javax.swing.JPanel jPanelRablero;
    private javax.swing.JLabel labelNombre0;
    private javax.swing.JLabel labelNombreX;
    private javax.swing.JLabel turno;
    // End of variables declaration//GEN-END:variables
}
